// Copyright 2011 Utkan Güngördü. All rights reserved.
// Use of this source code is governed by a BSD-style
// See the LICENSE file of the official Go distrubtion.

package extractor

//#include <extractor.h>
import "C"

const (
	VERSION = C.EXTRACTOR_VERSION


	OPTION_DEFAULT_POLICY = C.EXTRACTOR_OPTION_DEFAULT_POLICY
    OPTION_OUT_OF_PROCESS_NO_RESTART = C.EXTRACTOR_OPTION_OUT_OF_PROCESS_NO_RESTART
    OPTION_IN_PROCESS = C.EXTRACTOR_OPTION_IN_PROCESS
    OPTION_DISABLED = C.EXTRACTOR_OPTION_DISABLED


	METAFORMAT_UNKNOWN = C.EXTRACTOR_METAFORMAT_UNKNOWN
	METAFORMAT_UTF8 = C.EXTRACTOR_METAFORMAT_UTF8
	METAFORMAT_BINARY = C.EXTRACTOR_METAFORMAT_BINARY
	METAFORMAT_C_STRING = C.EXTRACTOR_METAFORMAT_C_STRING


	METATYPE_RESERVED = C.EXTRACTOR_METATYPE_RESERVED
	METATYPE_MIMETYPE = C.EXTRACTOR_METATYPE_MIMETYPE
	METATYPE_FILENAME = C.EXTRACTOR_METATYPE_FILENAME
	METATYPE_COMMENT = C.EXTRACTOR_METATYPE_COMMENT

		/* Standard types from bibtex */
	METATYPE_TITLE = C.EXTRACTOR_METATYPE_TITLE
	METATYPE_BOOK_TITLE = C.EXTRACTOR_METATYPE_BOOK_TITLE
	METATYPE_BOOK_EDITION = C.EXTRACTOR_METATYPE_BOOK_EDITION
	METATYPE_BOOK_CHAPTER_NUMBER = C.EXTRACTOR_METATYPE_BOOK_CHAPTER_NUMBER
	METATYPE_JOURNAL_NAME = C.EXTRACTOR_METATYPE_JOURNAL_NAME
	METATYPE_JOURNAL_VOLUME = C.EXTRACTOR_METATYPE_JOURNAL_VOLUME
	METATYPE_JOURNAL_NUMBER = C.EXTRACTOR_METATYPE_JOURNAL_NUMBER
	METATYPE_PAGE_COUNT = C.EXTRACTOR_METATYPE_PAGE_COUNT
	METATYPE_PAGE_RANGE = C.EXTRACTOR_METATYPE_PAGE_RANGE
	METATYPE_AUTHOR_NAME = C.EXTRACTOR_METATYPE_AUTHOR_NAME
	METATYPE_AUTHOR_EMAIL = C.EXTRACTOR_METATYPE_AUTHOR_EMAIL
	METATYPE_AUTHOR_INSTITUTION = C.EXTRACTOR_METATYPE_AUTHOR_INSTITUTION
	METATYPE_PUBLISHER = C.EXTRACTOR_METATYPE_PUBLISHER
	METATYPE_PUBLISHER_ADDRESS = C.EXTRACTOR_METATYPE_PUBLISHER_ADDRESS
	METATYPE_PUBLISHER_INSTITUTION = C.EXTRACTOR_METATYPE_PUBLISHER_INSTITUTION
	METATYPE_PUBLISHER_SERIES = C.EXTRACTOR_METATYPE_PUBLISHER_SERIES
	METATYPE_PUBLICATION_TYPE = C.EXTRACTOR_METATYPE_PUBLICATION_TYPE
	METATYPE_PUBLICATION_YEAR = C.EXTRACTOR_METATYPE_PUBLICATION_YEAR
	METATYPE_PUBLICATION_MONTH = C.EXTRACTOR_METATYPE_PUBLICATION_MONTH
	METATYPE_PUBLICATION_DAY = C.EXTRACTOR_METATYPE_PUBLICATION_DAY
	METATYPE_PUBLICATION_DATE = C.EXTRACTOR_METATYPE_PUBLICATION_DATE
	METATYPE_BIBTEX_EPRINT = C.EXTRACTOR_METATYPE_BIBTEX_EPRINT
	METATYPE_BIBTEX_ENTRY_TYPE = C.EXTRACTOR_METATYPE_BIBTEX_ENTRY_TYPE
	METATYPE_LANGUAGE = C.EXTRACTOR_METATYPE_LANGUAGE
	METATYPE_CREATION_TIME = C.EXTRACTOR_METATYPE_CREATION_TIME
	METATYPE_URL = C.EXTRACTOR_METATYPE_URL

		/* "unique" document identifiers */
	METATYPE_URI = C.EXTRACTOR_METATYPE_URI
	METATYPE_ISRC = C.EXTRACTOR_METATYPE_ISRC
	METATYPE_HASH_MD4 = C.EXTRACTOR_METATYPE_HASH_MD4
	METATYPE_HASH_MD5 = C.EXTRACTOR_METATYPE_HASH_MD5
	METATYPE_HASH_SHA0 = C.EXTRACTOR_METATYPE_HASH_SHA0
	METATYPE_HASH_SHA1 = C.EXTRACTOR_METATYPE_HASH_SHA1
	METATYPE_HASH_RMD160 = C.EXTRACTOR_METATYPE_HASH_RMD160

		/* identifiers of a location */
	METATYPE_GPS_LATITUDE_REF = C.EXTRACTOR_METATYPE_GPS_LATITUDE_REF
	METATYPE_GPS_LATITUDE = C.EXTRACTOR_METATYPE_GPS_LATITUDE
	METATYPE_GPS_LONGITUDE_REF = C.EXTRACTOR_METATYPE_GPS_LONGITUDE_REF
	METATYPE_GPS_LONGITUDE = C.EXTRACTOR_METATYPE_GPS_LONGITUDE
	METATYPE_LOCATION_CITY = C.EXTRACTOR_METATYPE_LOCATION_CITY
	METATYPE_LOCATION_SUBLOCATION = C.EXTRACTOR_METATYPE_LOCATION_SUBLOCATION
	METATYPE_LOCATION_COUNTRY = C.EXTRACTOR_METATYPE_LOCATION_COUNTRY
	METATYPE_LOCATION_COUNTRY_CODE = C.EXTRACTOR_METATYPE_LOCATION_COUNTRY_CODE

		/* generic attributes */
	METATYPE_UNKNOWN = C.EXTRACTOR_METATYPE_UNKNOWN
	METATYPE_DESCRIPTION = C.EXTRACTOR_METATYPE_DESCRIPTION
	METATYPE_COPYRIGHT = C.EXTRACTOR_METATYPE_COPYRIGHT
	METATYPE_RIGHTS = C.EXTRACTOR_METATYPE_RIGHTS
	METATYPE_KEYWORDS = C.EXTRACTOR_METATYPE_KEYWORDS
	METATYPE_ABSTRACT = C.EXTRACTOR_METATYPE_ABSTRACT
	METATYPE_SUMMARY = C.EXTRACTOR_METATYPE_SUMMARY
	METATYPE_SUBJECT = C.EXTRACTOR_METATYPE_SUBJECT
	METATYPE_CREATOR = C.EXTRACTOR_METATYPE_CREATOR
	METATYPE_FORMAT = C.EXTRACTOR_METATYPE_FORMAT
	METATYPE_FORMAT_VERSION = C.EXTRACTOR_METATYPE_FORMAT_VERSION

		/* processing history */
	METATYPE_CREATED_BY_SOFTWARE = C.EXTRACTOR_METATYPE_CREATED_BY_SOFTWARE
	METATYPE_UNKNOWN_DATE = C.EXTRACTOR_METATYPE_UNKNOWN_DATE
	METATYPE_CREATION_DATE = C.EXTRACTOR_METATYPE_CREATION_DATE
	METATYPE_MODIFICATION_DATE = C.EXTRACTOR_METATYPE_MODIFICATION_DATE
	METATYPE_LAST_PRINTED = C.EXTRACTOR_METATYPE_LAST_PRINTED
	METATYPE_LAST_SAVED_BY = C.EXTRACTOR_METATYPE_LAST_SAVED_BY
	METATYPE_TOTAL_EDITING_TIME = C.EXTRACTOR_METATYPE_TOTAL_EDITING_TIME
	METATYPE_EDITING_CYCLES = C.EXTRACTOR_METATYPE_EDITING_CYCLES
	METATYPE_MODIFIED_BY_SOFTWARE = C.EXTRACTOR_METATYPE_MODIFIED_BY_SOFTWARE
	METATYPE_REVISION_HISTORY = C.EXTRACTOR_METATYPE_REVISION_HISTORY

	METATYPE_EMBEDDED_FILE_SIZE = C.EXTRACTOR_METATYPE_EMBEDDED_FILE_SIZE
	METATYPE_FINDER_FILE_TYPE = C.EXTRACTOR_METATYPE_FINDER_FILE_TYPE
	METATYPE_FINDER_FILE_CREATOR = C.EXTRACTOR_METATYPE_FINDER_FILE_CREATOR

		/* software package specifics (deb, rpm, tgz, elf) */
	METATYPE_PACKAGE_NAME = C.EXTRACTOR_METATYPE_PACKAGE_NAME
	METATYPE_PACKAGE_VERSION = C.EXTRACTOR_METATYPE_PACKAGE_VERSION
	METATYPE_SECTION = C.EXTRACTOR_METATYPE_SECTION
	METATYPE_UPLOAD_PRIORITY = C.EXTRACTOR_METATYPE_UPLOAD_PRIORITY
	METATYPE_PACKAGE_DEPENDENCY = C.EXTRACTOR_METATYPE_PACKAGE_DEPENDENCY
	METATYPE_PACKAGE_CONFLICTS = C.EXTRACTOR_METATYPE_PACKAGE_CONFLICTS
	METATYPE_PACKAGE_REPLACES = C.EXTRACTOR_METATYPE_PACKAGE_REPLACES
	METATYPE_PACKAGE_PROVIDES = C.EXTRACTOR_METATYPE_PACKAGE_PROVIDES
	METATYPE_PACKAGE_RECOMMENDS = C.EXTRACTOR_METATYPE_PACKAGE_RECOMMENDS
	METATYPE_PACKAGE_SUGGESTS = C.EXTRACTOR_METATYPE_PACKAGE_SUGGESTS
	METATYPE_PACKAGE_MAINTAINER = C.EXTRACTOR_METATYPE_PACKAGE_MAINTAINER
	METATYPE_PACKAGE_INSTALLED_SIZE = C.EXTRACTOR_METATYPE_PACKAGE_INSTALLED_SIZE
	METATYPE_PACKAGE_SOURCE = C.EXTRACTOR_METATYPE_PACKAGE_SOURCE
	METATYPE_PACKAGE_ESSENTIAL = C.EXTRACTOR_METATYPE_PACKAGE_ESSENTIAL
	METATYPE_TARGET_ARCHITECTURE = C.EXTRACTOR_METATYPE_TARGET_ARCHITECTURE
	METATYPE_PACKAGE_PRE_DEPENDENCY = C.EXTRACTOR_METATYPE_PACKAGE_PRE_DEPENDENCY
	METATYPE_LICENSE = C.EXTRACTOR_METATYPE_LICENSE
	METATYPE_PACKAGE_DISTRIBUTION = C.EXTRACTOR_METATYPE_PACKAGE_DISTRIBUTION
	METATYPE_BUILDHOST = C.EXTRACTOR_METATYPE_BUILDHOST
	METATYPE_VENDOR = C.EXTRACTOR_METATYPE_VENDOR
	METATYPE_TARGET_OS = C.EXTRACTOR_METATYPE_TARGET_OS
	METATYPE_SOFTWARE_VERSION = C.EXTRACTOR_METATYPE_SOFTWARE_VERSION
	METATYPE_TARGET_PLATFORM = C.EXTRACTOR_METATYPE_TARGET_PLATFORM
	METATYPE_RESOURCE_TYPE = C.EXTRACTOR_METATYPE_RESOURCE_TYPE
	METATYPE_LIBRARY_SEARCH_PATH = C.EXTRACTOR_METATYPE_LIBRARY_SEARCH_PATH
	METATYPE_LIBRARY_DEPENDENCY = C.EXTRACTOR_METATYPE_LIBRARY_DEPENDENCY

		/* photography specifics */
	METATYPE_CAMERA_MAKE = C.EXTRACTOR_METATYPE_CAMERA_MAKE
	METATYPE_CAMERA_MODEL = C.EXTRACTOR_METATYPE_CAMERA_MODEL
	METATYPE_EXPOSURE = C.EXTRACTOR_METATYPE_EXPOSURE
	METATYPE_APERTURE = C.EXTRACTOR_METATYPE_APERTURE
	METATYPE_EXPOSURE_BIAS = C.EXTRACTOR_METATYPE_EXPOSURE_BIAS
	METATYPE_FLASH = C.EXTRACTOR_METATYPE_FLASH
	METATYPE_FLASH_BIAS = C.EXTRACTOR_METATYPE_FLASH_BIAS
	METATYPE_FOCAL_LENGTH = C.EXTRACTOR_METATYPE_FOCAL_LENGTH
	METATYPE_FOCAL_LENGTH_35MM = C.EXTRACTOR_METATYPE_FOCAL_LENGTH_35MM
	METATYPE_ISO_SPEED = C.EXTRACTOR_METATYPE_ISO_SPEED
	METATYPE_EXPOSURE_MODE = C.EXTRACTOR_METATYPE_EXPOSURE_MODE
	METATYPE_METERING_MODE = C.EXTRACTOR_METATYPE_METERING_MODE
	METATYPE_MACRO_MODE = C.EXTRACTOR_METATYPE_MACRO_MODE
	METATYPE_IMAGE_QUALITY = C.EXTRACTOR_METATYPE_IMAGE_QUALITY
	METATYPE_WHITE_BALANCE = C.EXTRACTOR_METATYPE_WHITE_BALANCE
	METATYPE_ORIENTATION = C.EXTRACTOR_METATYPE_ORIENTATION
	METATYPE_MAGNIFICATION = C.EXTRACTOR_METATYPE_MAGNIFICATION

		/* image specifics */
	METATYPE_IMAGE_DIMENSIONS = C.EXTRACTOR_METATYPE_IMAGE_DIMENSIONS
	METATYPE_PRODUCED_BY_SOFTWARE = C.EXTRACTOR_METATYPE_PRODUCED_BY_SOFTWARE
	METATYPE_THUMBNAIL = C.EXTRACTOR_METATYPE_THUMBNAIL
	METATYPE_IMAGE_RESOLUTION = C.EXTRACTOR_METATYPE_IMAGE_RESOLUTION
	METATYPE_SOURCE = C.EXTRACTOR_METATYPE_SOURCE

		/* (text) document processing specifics */
	METATYPE_CHARACTER_SET = C.EXTRACTOR_METATYPE_CHARACTER_SET
	METATYPE_LINE_COUNT = C.EXTRACTOR_METATYPE_LINE_COUNT
	METATYPE_PARAGRAPH_COUNT = C.EXTRACTOR_METATYPE_PARAGRAPH_COUNT
	METATYPE_WORD_COUNT = C.EXTRACTOR_METATYPE_WORD_COUNT
	METATYPE_CHARACTER_COUNT = C.EXTRACTOR_METATYPE_CHARACTER_COUNT
	METATYPE_PAGE_ORIENTATION = C.EXTRACTOR_METATYPE_PAGE_ORIENTATION
	METATYPE_PAPER_SIZE = C.EXTRACTOR_METATYPE_PAPER_SIZE
	METATYPE_TEMPLATE = C.EXTRACTOR_METATYPE_TEMPLATE
	METATYPE_COMPANY = C.EXTRACTOR_METATYPE_COMPANY
	METATYPE_MANAGER = C.EXTRACTOR_METATYPE_MANAGER
	METATYPE_REVISION_NUMBER = C.EXTRACTOR_METATYPE_REVISION_NUMBER

		/* music / video specifics */
	METATYPE_DURATION = C.EXTRACTOR_METATYPE_DURATION
	METATYPE_ALBUM = C.EXTRACTOR_METATYPE_ALBUM
	METATYPE_ARTIST = C.EXTRACTOR_METATYPE_ARTIST
	METATYPE_GENRE = C.EXTRACTOR_METATYPE_GENRE
	METATYPE_TRACK_NUMBER = C.EXTRACTOR_METATYPE_TRACK_NUMBER
	METATYPE_DISC_NUMBER = C.EXTRACTOR_METATYPE_DISC_NUMBER
	METATYPE_PERFORMER = C.EXTRACTOR_METATYPE_PERFORMER
	METATYPE_CONTACT_INFORMATION = C.EXTRACTOR_METATYPE_CONTACT_INFORMATION
	METATYPE_SONG_VERSION = C.EXTRACTOR_METATYPE_SONG_VERSION
	METATYPE_PICTURE = C.EXTRACTOR_METATYPE_PICTURE
	METATYPE_COVER_PICTURE = C.EXTRACTOR_METATYPE_COVER_PICTURE
	METATYPE_CONTRIBUTOR_PICTURE = C.EXTRACTOR_METATYPE_CONTRIBUTOR_PICTURE
	METATYPE_EVENT_PICTURE = C.EXTRACTOR_METATYPE_EVENT_PICTURE
	METATYPE_LOGO = C.EXTRACTOR_METATYPE_LOGO
	METATYPE_BROADCAST_TELEVISION_SYSTEM = C.EXTRACTOR_METATYPE_BROADCAST_TELEVISION_SYSTEM
	METATYPE_SOURCE_DEVICE = C.EXTRACTOR_METATYPE_SOURCE_DEVICE
	METATYPE_DISCLAIMER = C.EXTRACTOR_METATYPE_DISCLAIMER
	METATYPE_WARNING = C.EXTRACTOR_METATYPE_WARNING
	METATYPE_PAGE_ORDER = C.EXTRACTOR_METATYPE_PAGE_ORDER
	METATYPE_WRITER = C.EXTRACTOR_METATYPE_WRITER
	METATYPE_PRODUCT_VERSION = C.EXTRACTOR_METATYPE_PRODUCT_VERSION
	METATYPE_CONTRIBUTOR_NAME = C.EXTRACTOR_METATYPE_CONTRIBUTOR_NAME
	METATYPE_MOVIE_DIRECTOR = C.EXTRACTOR_METATYPE_MOVIE_DIRECTOR
	METATYPE_NETWORK_NAME = C.EXTRACTOR_METATYPE_NETWORK_NAME
	METATYPE_SHOW_NAME = C.EXTRACTOR_METATYPE_SHOW_NAME
	METATYPE_CHAPTER_NAME = C.EXTRACTOR_METATYPE_CHAPTER_NAME
	METATYPE_SONG_COUNT = C.EXTRACTOR_METATYPE_SONG_COUNT
	METATYPE_STARTING_SONG = C.EXTRACTOR_METATYPE_STARTING_SONG
	METATYPE_PLAY_COUNTER = C.EXTRACTOR_METATYPE_PLAY_COUNTER
	METATYPE_CONDUCTOR = C.EXTRACTOR_METATYPE_CONDUCTOR
	METATYPE_INTERPRETATION = C.EXTRACTOR_METATYPE_INTERPRETATION
	METATYPE_COMPOSER = C.EXTRACTOR_METATYPE_COMPOSER
	METATYPE_BEATS_PER_MINUTE = C.EXTRACTOR_METATYPE_BEATS_PER_MINUTE
	METATYPE_ENCODED_BY = C.EXTRACTOR_METATYPE_ENCODED_BY
	METATYPE_ORIGINAL_TITLE = C.EXTRACTOR_METATYPE_ORIGINAL_TITLE
	METATYPE_ORIGINAL_ARTIST = C.EXTRACTOR_METATYPE_ORIGINAL_ARTIST
	METATYPE_ORIGINAL_WRITER = C.EXTRACTOR_METATYPE_ORIGINAL_WRITER
	METATYPE_ORIGINAL_RELEASE_YEAR = C.EXTRACTOR_METATYPE_ORIGINAL_RELEASE_YEAR
	METATYPE_ORIGINAL_PERFORMER = C.EXTRACTOR_METATYPE_ORIGINAL_PERFORMER
	METATYPE_LYRICS = C.EXTRACTOR_METATYPE_LYRICS
	METATYPE_POPULARITY_METER = C.EXTRACTOR_METATYPE_POPULARITY_METER
	METATYPE_LICENSEE = C.EXTRACTOR_METATYPE_LICENSEE
	METATYPE_MUSICIAN_CREDITS_LIST = C.EXTRACTOR_METATYPE_MUSICIAN_CREDITS_LIST
	METATYPE_MOOD = C.EXTRACTOR_METATYPE_MOOD
	METATYPE_SUBTITLE = C.EXTRACTOR_METATYPE_SUBTITLE

		/* GNUnet specific values (never extracted) */
	METATYPE_GNUNET_DISPLAY_TYPE = C.EXTRACTOR_METATYPE_GNUNET_DISPLAY_TYPE
	METATYPE_GNUNET_FULL_DATA = C.EXTRACTOR_METATYPE_GNUNET_FULL_DATA
	METATYPE_RATING = C.EXTRACTOR_METATYPE_RATING
	METATYPE_ORGANIZATION = C.EXTRACTOR_METATYPE_ORGANIZATION
	METATYPE_RIPPER = C.EXTRACTOR_METATYPE_RIPPER
	METATYPE_PRODUCER = C.EXTRACTOR_METATYPE_PRODUCER
	METATYPE_GROUP = C.EXTRACTOR_METATYPE_GROUP

	METATYPE_LAST = C.EXTRACTOR_METATYPE_LAST
)

